# Generated by Django 3.0.1 on 2020-01-02 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gantt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='effect',
            name='attack_type',
            field=models.CharField(default=3, max_length=255),
        ),
    ]
