from django.shortcuts import get_object_or_404, render
from .models import Character,Effect
from django.http import Http404
from django.http import HttpResponse
import plotly.figure_factory as ff


def index(request):
    latest_character_list = Character.objects.order_by('pk')
    context = {'latest_character_list': latest_character_list}

    df = [dict(Task="Job Skill 1", Start='2016-01-01 00:00:00', Finish='2016-01-01 00:00:30'),
      dict(Task="Job Skill 2", Start='2016-01-01 00:00:20', Finish='2016-01-01 00:01:30')]

    fig = ff.create_gantt(df)
    fig.layout.xaxis.tickformat = '%M:%S'
    string = fig.to_html()
    return render(request, 'gantt/index.html', {"context" : context , "chart" : string}) 


def character_list(request):
    latest_character_list = Character.objects.order_by('pk')
    context = {'latest_character_list': latest_character_list}
    return render(request,'gantt/detail.html',{"context":context})

def create_data(request):
    try:
        Character.objects.get(name='宮子')
        return HttpResponse("成功了 別再按了")
    except:
        Character.objects.create(name='宮子',photo='static/gantt/images/miyako.png')
        Character.objects.create(name='莉瑪',photo='static/gantt/images/rima.png')
        Character.objects.create(name='空花',photo='static/gantt/images/kuka.png')
        Character.objects.create(name='純',photo='static/gantt/images/jun.png')
        Character.objects.create(name='空花(江戶',photo='static/gantt/images/kukaO.png')
        Character.objects.create(name='彾(新年',photo='static/gantt/images/reiNew.png')
        Character.objects.create(name='貪吃佩可',photo='static/gantt/images/peko.png')
        Character.objects.create(name='流夏',photo='static/gantt/images/ruka.png')
        Character.objects.create(name='望',photo='static/gantt/images/nozomi.png')
        Character.objects.create(name='茅衣未',photo='static/gantt/images/muimi.png')
        Character.objects.create(name='真琴',photo='static/gantt/images/makoto.png')
        Character.objects.create(name='日和(新年',photo='static/gantt/images/hioriNew.png')
        Character.objects.create(name='妮諾(江戶',photo='static/gantt/images/ninoO.png')
        Character.objects.create(name='秋乃',photo='static/gantt/images/akino.png')
        Character.objects.create(name='真琴(夏日',photo='static/gantt/images/makotoSummer.png')
        Character.objects.create(name='茉莉',photo='static/gantt/images/matsuri.png')
        Character.objects.create(name='惠理子',photo='static/gantt/images/eriko.png')
        Character.objects.create(name='綾音(聖誕',photo='static/gantt/images/ayaneXmas.png')
        Character.objects.create(name='紡希',photo='static/gantt/images/sumugi.png')
        Character.objects.create(name='日和',photo='static/gantt/images/hiyori.png')
        Character.objects.create(name='炸彈超人',photo='static/gantt/images/bomb.png')
        Character.objects.create(name='綾音',photo='static/gantt/images/ayane.png')
        Character.objects.create(name='珠希',photo='static/gantt/images/tamagi.png')
        Character.objects.create(name='智',photo='static/gantt/images/tomo.png')
        Character.objects.create(name='珠希(夏日',photo='static/gantt/images/tamagiSummer.png')
        Character.objects.create(name='貪吃佩可(夏日',photo='static/gantt/images/pekoSummer.png')
        Character.objects.create(name='胡桃',photo='static/gantt/images/kurumi.png')
        Character.objects.create(name='吉塔',photo='static/gantt/images/jita.png')
        Character.objects.create(name='彾',photo='static/gantt/images/rei.png')
        Character.objects.create(name='靜流',photo='static/gantt/images/shizuru.png')
        Character.objects.create(name='克莉絲提娜',photo='static/gantt/images/chris.png')
        Character.objects.create(name='胡桃(聖誕',photo='static/gantt/images/kurumiXmas.png')
        Character.objects.create(name='美美',photo='static/gantt/images/mimi.png')
        Character.objects.create(name='忍',photo='static/gantt/images/shinobu.png')
        Character.objects.create(name='靜流(情人節',photo='static/gantt/images/shizuruV.png')
        Character.objects.create(name='優花梨',photo='static/gantt/images/yukari.png')
        Character.objects.create(name='莫妮卡',photo='static/gantt/images/manika.png')
        Character.objects.create(name='妮諾',photo='static/gantt/images/nino.png')
        Character.objects.create(name='伊莉雅',photo='static/gantt/images/iria.png')
        Character.objects.create(name='香織(夏日',photo='static/gantt/images/kaoriSummer.png')
        Character.objects.create(name='咲戀',photo='static/gantt/images/saren.png')
        Character.objects.create(name='杏奈',photo='static/gantt/images/anna.png')
        Character.objects.create(name='忍(萬聖節',photo='static/gantt/images/shinobuHell.png')
        Character.objects.create(name='可可蘿',photo='static/gantt/images/kokoro.png')
        Character.objects.create(name='深月',photo='static/gantt/images/misuki.png')
        Character.objects.create(name='茜里',photo='static/gantt/images/akari.png')
        Character.objects.create(name='依里',photo='static/gantt/images/yuri.png')
        Character.objects.create(name='咲戀(夏日',photo='static/gantt/images/sarenSummer.png')
        Character.objects.create(name='宮子(萬聖節',photo='static/gantt/images/miyakoHell.png')
        Character.objects.create(name='亞里莎',photo='static/gantt/images/arisa.png')
        Character.objects.create(name='安',photo='static/gantt/images/ann.png')
        Character.objects.create(name='露',photo='static/gantt/images/ru.png')
        Character.objects.create(name='璃乃',photo='static/gantt/images/rino.png')
        Character.objects.create(name='玲奈',photo='static/gantt/images/suzuna.png')
        Character.objects.create(name='玲奈(夏日',photo='static/gantt/images/suzunaSummer.png')
        Character.objects.create(name='栞',photo='static/gantt/images/shiori.png')
        Character.objects.create(name='伊緒',photo='static/gantt/images/io.png')
        Character.objects.create(name='伊緒(夏日',photo='static/gantt/images/ioSummer.png')
        Character.objects.create(name='霞',photo='static/gantt/images/kazami.png')
        Character.objects.create(name='美里',photo='static/gantt/images/misato.png')
        Character.objects.create(name='七七香',photo='static/gantt/images/nanaka.png')
        Character.objects.create(name='優依(新年',photo='static/gantt/images/yuiNew.png')
        Character.objects.create(name='凱留',photo='static/gantt/images/kyaru.png')
        Character.objects.create(name='初音',photo='static/gantt/images/hatsune.png')
        Character.objects.create(name='美咲',photo='static/gantt/images/misaki.png')
        Character.objects.create(name='千歌(聖誕',photo='static/gantt/images/chikaXmas.png')
        Character.objects.create(name='凱留(夏日',photo='static/gantt/images/kyaruSummer.png')
        Character.objects.create(name='碧',photo='static/gantt/images/aoi.png')
        Character.objects.create(name='千歌',photo='static/gantt/images/chika.png')
        Character.objects.create(name='真步(夏日',photo='static/gantt/images/makotoSummer.png')
        Character.objects.create(name='真步',photo='static/gantt/images/maho.png')
        Character.objects.create(name='優依',photo='static/gantt/images/yui.png')
        Character.objects.create(name='雪',photo='static/gantt/images/yuki.png')
        Character.objects.create(name='鏡華',photo='static/gantt/images/kyoka.png')
        Character.objects.create(name='美咲(萬聖',photo='static/gantt/images/misakiHell.png')
        Character.objects.create(name='香織',photo='static/gantt/images/kaori.png')
        Effect.objects.create(character_id=Character.objects.get(name='宮子'),skill_name = '1',skill_type=1,duration=3,addtional_time=0.01,description='無敵',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='宮子'),skill_name = '2',skill_type=2,duration=0,addtional_time=0,description='補血',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='莉瑪'),skill_name = '1',skill_type=1,duration=16,addtional_time=0,description='增加物防',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='莉瑪'),skill_name = '2',skill_type=2,duration=1.5,addtional_time=0,description='麻痹',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='空花'),skill_name = '1',skill_type=1,duration=12,addtional_time=0,description='增加物防',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='空花'),skill_name = '2',skill_type=1,duration=0,addtional_time=0,description='補血',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='空花'),skill_name = '3',skill_type=1,duration=12,addtional_time=0,description='增加物攻',is_weapon=1)
        Effect.objects.create(character_id=Character.objects.get(name='空花'),skill_name = '4',skill_type=1,duration=12,addtional_time=0,description='行動速度上升20%',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='空花'),skill_name = '5',skill_type=2,duration=12,addtional_time=0,description='降低敵人物防',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='純'),skill_name = '1',skill_type=1,duration=12,addtional_time=0,description='增加物攻',is_weapon=1)
        Effect.objects.create(character_id=Character.objects.get(name='純'),skill_name = '2',skill_type=1,duration=12,addtional_time=0,description='行動速度上升20%',is_weapon=1)
        Effect.objects.create(character_id=Character.objects.get(name='純'),skill_name = '3',skill_type=2,duration=12,addtional_time=0,description='降低敵人物防',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='空花(江戶'),skill_name = '1',skill_type=1,duration=12,addtional_time=0,description='增加魔攻',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='空花(江戶'),skill_name = '2',skill_type=2,duration=12,addtional_time=0,description='降低敵人魔防',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='彾(新年'),skill_name = '1',skill_type=1,duration=5,addtional_time=0.05,description='挑釁',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='彾(新年'),skill_name = '2',skill_type=1,duration=12,addtional_time=0,description='降低敵人物防',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='彾(新年'),skill_name = '3',skill_type=2,duration=12,addtional_time=0,description='傷害減免',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='彾(新年'),skill_name = '4',skill_type=2,duration=12,addtional_time=0,description='增加魔防',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='貪吃佩可'),skill_name = '1',skill_type=1,duration=12,addtional_time=0,description='增加魔防',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='貪吃佩可'),skill_name = '2',skill_type=2,duration=8,addtional_time=0,description='傷害減免',is_weapon=1)
        Effect.objects.create(character_id=Character.objects.get(name='流夏'),skill_name = '1',skill_type=1,duration=5,addtional_time=0.05,description='挑釁',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='流夏'),skill_name = '2',skill_type=1,duration=12,addtional_time=0,description='降低敵人物防',is_weapon=1)
        Effect.objects.create(character_id=Character.objects.get(name='流夏'),skill_name = '3',skill_type=2,duration=12,addtional_time=0,description='增加物防',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='望'),skill_name = '1',skill_type=1,duration=1.5,addtional_time=0,description='麻痹',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='望'),skill_name = '2',skill_type=1,duration=12,addtional_time=0,description='降低敵人物攻',is_weapon=1)
        Effect.objects.create(character_id=Character.objects.get(name='茅衣未'),skill_name = '1',skill_type=1,duration=1.5,addtional_time=0,description='麻痹',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='茅衣未'),skill_name = '2',skill_type=2,duration=12,addtional_time=0,description='降低敵人物防',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='真琴'),skill_name = '1',skill_type=1,duration=12,addtional_time=0,description='增加物攻',is_weapon=1)
        Effect.objects.create(character_id=Character.objects.get(name='真琴'),skill_name = '2',skill_type=2,duration=12,addtional_time=0,description='降低敵人物防',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='日和(新年'),skill_name = '1',skill_type=1,duration=12,addtional_time=0,description='增加物攻',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='日和(新年'),skill_name = '2',skill_type=2,duration=0,addtional_time=0,description='攻擊',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='妮諾(江戶'),skill_name = '1',skill_type=1,duration=12,addtional_time=0,description='降低敵人物防',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='妮諾(江戶'),skill_name = '2',skill_type=2,duration=12,addtional_time=0,description='行動速度上升100%',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='秋乃'),skill_name = '1',skill_type=1,duration=12,addtional_time=0,description='增加物攻',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='秋乃'),skill_name = '2',skill_type=1,duration=12,addtional_time=0,description='TP上升',is_weapon=1)
        Effect.objects.create(character_id=Character.objects.get(name='秋乃'),skill_name = '3',skill_type=1,duration=5,addtional_time=0,description='挑釁',is_weapon=1)
        Effect.objects.create(character_id=Character.objects.get(name='真琴(夏日'),skill_name = '1',skill_type=1,duration=12,addtional_time=0,description='降低敵人物防',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='真琴(夏日'),skill_name = '2',skill_type=2,duration=180,addtional_time=0,description='增加物攻',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='茉莉'),skill_name = '1',skill_type=1,duration=2,addtional_time=0,description='麻痹',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='茉莉'),skill_name = '2',skill_type=1,duration=12,addtional_time=0,description='增加魔防',is_weapon=1)
        Effect.objects.create(character_id=Character.objects.get(name='茉莉'),skill_name = '3',skill_type=1,duration=12,addtional_time=0,description='增加物防',is_weapon=1)
        Effect.objects.create(character_id=Character.objects.get(name='茉莉'),skill_name = '4',skill_type=2,duration=0.05,addtional_time=0,description='',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='惠理子'),skill_name = '1',skill_type=1,duration=0.05,addtional_time=0,description='',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='惠理子'),skill_name = '2',skill_type=2,duration=12,addtional_time=0,description='增加物攻',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='綾音(聖誕'),skill_name = '1',skill_type=1,duration=10,addtional_time=0,description='增加物攻',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='綾音(聖誕'),skill_name = '2',skill_type=2,duration=0.05,addtional_time=0,description='',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='紡希'),skill_name = '1',skill_type=1,duration=0.05,addtional_time=0,description='',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='紡希'),skill_name = '2',skill_type=1,duration=12,addtional_time=0,description='增加物攻',is_weapon=1)
        Effect.objects.create(character_id=Character.objects.get(name='紡希'),skill_name = '3',skill_type=1,duration=12,addtional_time=0,description='增加物防',is_weapon=1)
        Effect.objects.create(character_id=Character.objects.get(name='紡希'),skill_name = '4',skill_type=2,duration=12,addtional_time=0,description='降低敵人移動速度',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='紡希'),skill_name = '5',skill_type=2,duration=12,addtional_time=0,description='降低敵人行動速度',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='日和'),skill_name = '1',skill_type=1,duration=0.05,addtional_time=0,description='',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='日和'),skill_name = '2',skill_type=2,duration=12,addtional_time=0,description='增加物攻',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='炸彈超人'),skill_name = '1',skill_type=1,duration=8,addtional_time=0,description='黑暗',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='炸彈超人'),skill_name = '2',skill_type=1,duration=180,addtional_time=0,description='降低敵人物攻',is_weapon=1)
        Effect.objects.create(character_id=Character.objects.get(name='炸彈超人'),skill_name = '3',skill_type=2,duration=90,addtional_time=0,description='降低敵人物攻',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='炸彈超人'),skill_name = '4',skill_type=2,duration=90,addtional_time=0,description='增加物攻',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='綾音'),skill_name = '1',skill_type=1,duration=1.5,addtional_time=0,description='麻痹',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='綾音'),skill_name = '2',skill_type=1,duration=10.5,addtional_time=0,description='降低敵人行動速度',is_weapon=1)
        Effect.objects.create(character_id=Character.objects.get(name='綾音'),skill_name = '3',skill_type=2,duration=12,addtional_time=0,description='降低敵人物防',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='珠希'),skill_name = '1',skill_type=1,duration=12,addtional_time=0,description='降低敵人魔攻',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='珠希'),skill_name = '2',skill_type=1,duration=1.5,addtional_time=0,description='麻痹',is_weapon=1)
        Effect.objects.create(character_id=Character.objects.get(name='珠希'),skill_name = '3',skill_type=2,duration=0.05,addtional_time=0,description='',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='智'),skill_name = '1',skill_type=1,duration=0.05,addtional_time=0,description='',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='智'),skill_name = '2',skill_type=2,duration=0.05,addtional_time=0,description='',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='珠希(夏日'),skill_name = '1',skill_type=1,duration=12,addtional_time=0,description='降低敵人物攻',is_weapon=1)
        Effect.objects.create(character_id=Character.objects.get(name='珠希(夏日'),skill_name = '2',skill_type=1,duration=12,addtional_time=0,description='增加物攻',is_weapon=1)
        Effect.objects.create(character_id=Character.objects.get(name='珠希(夏日'),skill_name = '3',skill_type=1,duration=0.05,addtional_time=0,description='',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='珠希(夏日'),skill_name = '4',skill_type=2,duration=12,addtional_time=0,description='增加物攻',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='珠希(夏日'),skill_name = '5',skill_type=2,duration=12,addtional_time=0,description='行動速度上升100%',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='惠理子'),skill_name = '1',skill_type=1,duration=12,addtional_time=0,description='增加物攻',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='惠理子'),skill_name = '2',skill_type=1,duration=7.5,addtional_time=0,description='增加物攻',is_weapon=1)
        Effect.objects.create(character_id=Character.objects.get(name='惠理子'),skill_name = '3',skill_type=1,duration=7.5,addtional_time=0,description='增加物理爆擊',is_weapon=1)
        Effect.objects.create(character_id=Character.objects.get(name='惠理子'),skill_name = '4',skill_type=2,duration=8,addtional_time=0,description='中毒',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='貪吃佩可(夏日'),skill_name = '1',skill_type=1,duration=12,addtional_time=0,description='增加物攻',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='貪吃佩可(夏日'),skill_name = '2',skill_type=1,duration=12,addtional_time=0,description='降低自身魔防',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='貪吃佩可(夏日'),skill_name = '3',skill_type=1,duration=12,addtional_time=0,description='增加物理爆擊',is_weapon=1)
        Effect.objects.create(character_id=Character.objects.get(name='胡桃'),skill_name = '1',skill_type=1,duration=12,addtional_time=0,description='增加雙防',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='胡桃'),skill_name = '2',skill_type=2,duration=1.5,addtional_time=0,description='麻痹',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='吉塔'),skill_name = '1',skill_type=1,duration=0.05,addtional_time=0,description='',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='吉塔'),skill_name = '2',skill_type=2,duration=0.05,addtional_time=0,description='',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='彾'),skill_name = '2',skill_type=1,duration=12,addtional_time=0,description='降低敵人物防',is_weapon=1)
        Effect.objects.create(character_id=Character.objects.get(name='彾'),skill_name = '3',skill_type=2,duration=0.05,addtional_time=0,description='',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='靜流'),skill_name = '1',skill_type=1,duration=0.05,addtional_time=0,description='',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='靜流'),skill_name = '2',skill_type=1,duration=12,addtional_time=0,description='增加物防',is_weapon=1)
        Effect.objects.create(character_id=Character.objects.get(name='靜流'),skill_name = '3',skill_type=2,duration=12,addtional_time=0,description='傷害減免',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='克莉絲提娜'),skill_name = '1',skill_type=1,duration=12,addtional_time=0,description='增加物攻',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='克莉絲提娜'),skill_name = '2',skill_type=1,duration=12,addtional_time=0,description='TP上升率增加',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='克莉絲提娜'),skill_name = '3',skill_type=2,duration=12,addtional_time=0,description='降低敵人物防',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='胡桃(聖誕'),skill_name = '1',skill_type=1,duration=10,addtional_time=0,description='增加物防',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='胡桃(聖誕'),skill_name = '2',skill_type=1,duration=12,addtional_time=0,description='增加物防',is_weapon=1)
        Effect.objects.create(character_id=Character.objects.get(name='美美'),skill_name = '1',skill_type=1,duration=0.05,addtional_time=0,description='',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='美美'),skill_name = '2',skill_type=2,duration=12,addtional_time=0,description='增加物攻',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='忍'),skill_name = '2',skill_type=1,duration=12,addtional_time=0,description='增加物攻',is_weapon=1)
        Effect.objects.create(character_id=Character.objects.get(name='忍'),skill_name = '3',skill_type=1,duration=12,addtional_time=0,description='增加物理爆擊',is_weapon=1)
        Effect.objects.create(character_id=Character.objects.get(name='忍'),skill_name = '4',skill_type=2,duration=12,addtional_time=0,description='降低敵人物防',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='靜流(情人節'),skill_name = '1',skill_type=1,duration=0.05,addtional_time=0,description='',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='靜流(情人節'),skill_name = '2',skill_type=2,duration=12,addtional_time=0,description='增加物攻',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='優花梨'),skill_name = '1',skill_type=1,duration=0.05,addtional_time=0,description='',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='優花梨'),skill_name = '2',skill_type=1,duration=12,addtional_time=0,description='增加魔防',is_weapon=1)
        Effect.objects.create(character_id=Character.objects.get(name='優花梨'),skill_name = '3',skill_type=1,duration=8.5,addtional_time=0,description='持續回血',is_weapon=1)
        Effect.objects.create(character_id=Character.objects.get(name='莫妮卡'),skill_name = '1',skill_type=1,duration=20,addtional_time=0,description='增加雙攻',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='莫妮卡'),skill_name = '2',skill_type=1,duration=20,addtional_time=0,description='增加行動速度',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='莫妮卡'),skill_name = '3',skill_type=2,duration=1.5,addtional_time=0,description='麻痹',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='妮諾'),skill_name = '1',skill_type=1,duration=0.05,addtional_time=0,description='',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='妮諾'),skill_name = '2',skill_type=2,duration=0.05,addtional_time=0,description='',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='伊莉雅'),skill_name = '1',skill_type=1,duration=12,addtional_time=0,description='增加魔攻',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='伊莉雅'),skill_name = '2',skill_type=2,duration=0.05,addtional_time=0,description='',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='香織(夏日'),skill_name = '1',skill_type=1,duration=0.05,addtional_time=0,description='',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='香織(夏日'),skill_name = '2',skill_type=2,duration=12,addtional_time=0,description='增加物攻',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='香織(夏日'),skill_name = '3',skill_type=2,duration=12,addtional_time=0,description='增加行動速度',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='咲戀'),skill_name = '1',skill_type=1,duration=0.05,addtional_time=0,description='',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='咲戀'),skill_name = '2',skill_type=2,duration=0.05,addtional_time=0,description='',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='杏奈'),skill_name = '1',skill_type=1,duration=0.05,addtional_time=0,description='',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='杏奈'),skill_name = '2',skill_type=1,duration=12,addtional_time=0,description='降低敵人魔防',is_weapon=1)
        Effect.objects.create(character_id=Character.objects.get(name='杏奈'),skill_name = '3',skill_type=2,duration=0.05,addtional_time=0,description='',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='忍(萬聖節'),skill_name = '1',skill_type=1,duration=12,addtional_time=0,description='增加物攻',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='忍(萬聖節'),skill_name = '2',skill_type=1,duration=12,addtional_time=0,description='增加物理爆擊',is_weapon=1)
        Effect.objects.create(character_id=Character.objects.get(name='可可蘿'),skill_name = '1',skill_type=1,duration=0.05,addtional_time=0,description='',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='可可蘿'),skill_name = '2',skill_type=1,duration=12,addtional_time=0,description='增加物攻',is_weapon=1)
        Effect.objects.create(character_id=Character.objects.get(name='可可蘿'),skill_name = '3',skill_type=1,duration=12,addtional_time=0,description='TP上升',is_weapon=1)
        Effect.objects.create(character_id=Character.objects.get(name='可可蘿'),skill_name = '4',skill_type=2,duration=12,addtional_time=0,description='行動速度上升20%',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='可可蘿'),skill_name = '5',skill_type=2,duration=12,addtional_time=0,description='增加物攻',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='深月'),skill_name = '1',skill_type=1,duration=12,addtional_time=0,description='詛咒',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='深月'),skill_name = '2',skill_type=1,duration=12,addtional_time=0,description='降低敵人行動速度',is_weapon=1)
        Effect.objects.create(character_id=Character.objects.get(name='深月'),skill_name = '3',skill_type=2,duration=12,addtional_time=0,description='降低敵人物防',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='茜里'),skill_name = '1',skill_type=1,duration=0.05,addtional_time=0,description='',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='茜里'),skill_name = '2',skill_type=1,duration=12,addtional_time=0,description='降低敵人魔防',is_weapon=1)
        Effect.objects.create(character_id=Character.objects.get(name='茜里'),skill_name = '3',skill_type=2,duration=12,addtional_time=0,description='降低敵人魔防',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='依里'),skill_name = '1',skill_type=1,duration=12,addtional_time=0,description='增加魔攻',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='依里'),skill_name = '2',skill_type=2,duration=0.05,addtional_time=0,description='',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='咲戀(夏日'),skill_name = '2',skill_type=2,duration=12,addtional_time=0,description='增加魔攻',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='咲戀(夏日'),skill_name = '3',skill_type=2,duration=12,addtional_time=0,description='增加物攻',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='咲戀(夏日'),skill_name = '4',skill_type=2,duration=12,addtional_time=0,description='增加物理爆擊',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='咲戀(夏日'),skill_name = '5',skill_type=2,duration=12,addtional_time=0,description='增加魔法爆擊',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='宮子(萬聖節'),skill_name = '1',skill_type=1,duration=1.8,addtional_time=0,description='麻痹',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='宮子(萬聖節'),skill_name = '2',skill_type=1,duration=8,addtional_time=0,description='恐慌',is_weapon=1)
        Effect.objects.create(character_id=Character.objects.get(name='宮子(萬聖節'),skill_name = '3',skill_type=2,duration=12,addtional_time=0,description='降低敵人物防',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='宮子(萬聖節'),skill_name = '4',skill_type=2,duration=12,addtional_time=0,description='降低敵人魔防',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='亞里莎'),skill_name = '1',skill_type=1,duration=8,addtional_time=0,description='降低敵人行動速度',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='亞里莎'),skill_name = '2',skill_type=1,duration=12,addtional_time=0,description='降低敵人魔攻',is_weapon=1)
        Effect.objects.create(character_id=Character.objects.get(name='亞里莎'),skill_name = '3',skill_type=2,duration=0.05,addtional_time=0,description='',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='安'),skill_name = '1',skill_type=1,duration=0.05,addtional_time=0,description='',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='安'),skill_name = '2',skill_type=2,duration=12,addtional_time=0,description='英靈加護',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='安'),skill_name = '3',skill_type=2,duration=12,addtional_time=0,description='增加魔攻',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='安'),skill_name = '4',skill_type=2,duration=12,addtional_time=0,description='行動速度上升',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='露'),skill_name = '1',skill_type=1,duration=0.05,addtional_time=0,description='',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='露'),skill_name = '2',skill_type=2,duration=0.05,addtional_time=0,description='',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='璃乃'),skill_name = '1',skill_type=1,duration=12,addtional_time=0,description='增加物攻',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='璃乃'),skill_name = '2',skill_type=1,duration=90,addtional_time=0,description='增加物理爆擊',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='璃乃'),skill_name = '3',skill_type=1,duration=12,addtional_time=0,description='增加行動速度',is_weapon=1)
        Effect.objects.create(character_id=Character.objects.get(name='璃乃'),skill_name = '4',skill_type=2,duration=0.05,addtional_time=0,description='',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='玲奈'),skill_name = '1',skill_type=1,duration=0.05,addtional_time=0,description='',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='玲奈'),skill_name = '2',skill_type=2,duration=12,addtional_time=0,description='增加物攻',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='玲奈(夏日'),skill_name = '1',skill_type=1,duration=0.05,addtional_time=0,description='',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='玲奈(夏日'),skill_name = '2',skill_type=2,duration=180,addtional_time=0,description='增加物攻',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='栞'),skill_name = '1',skill_type=1,duration=0.05,addtional_time=0,description='',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='栞'),skill_name = '2',skill_type=2,duration=0.05,addtional_time=0,description='',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='伊緒'),skill_name = '1',skill_type=1,duration=0.05,addtional_time=0,description='',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='伊緒'),skill_name = '2',skill_type=1,duration=12,addtional_time=0,description='降低敵人雙防',is_weapon=1)
        Effect.objects.create(character_id=Character.objects.get(name='伊緒(夏日'),skill_name = '1',skill_type=1,duration=0.05,addtional_time=0,description='',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='伊緒(夏日'),skill_name = '2',skill_type=1,duration=12,addtional_time=0,description='降低敵人魔防',is_weapon=1)
        Effect.objects.create(character_id=Character.objects.get(name='霞'),skill_name = '1',skill_type=1,duration=2.5,addtional_time=0,description='束縛',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='霞'),skill_name = '2',skill_type=2,duration=7.5,addtional_time=0,description='混亂',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='美里'),skill_name = '1',skill_type=1,duration=12,addtional_time=0,description='增加魔攻',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='美里'),skill_name = '2',skill_type=1,duration=12,addtional_time=0,description='增加魔法爆擊',is_weapon=1)
        Effect.objects.create(character_id=Character.objects.get(name='美里'),skill_name = '3',skill_type=2,duration=7,addtional_time=0,description='持續回血',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='七七香'),skill_name = '1',skill_type=1,duration=12,addtional_time=0,description='降低敵人魔防',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='七七香'),skill_name = '2',skill_type=2,duration=1.5,addtional_time=0,description='麻痹',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='優依(新年'),skill_name = '1',skill_type=1,duration=12,addtional_time=0,description='降低敵人雙攻',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='優依(新年'),skill_name = '2',skill_type=2,duration=12,addtional_time=0,description='增加魔攻',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='凱留'),skill_name = '1',skill_type=1,duration=0.05,addtional_time=0,description='',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='凱留'),skill_name = '2',skill_type=1,duration=12,addtional_time=0,description='降低敵人魔防',is_weapon=1)
        Effect.objects.create(character_id=Character.objects.get(name='凱留'),skill_name = '3',skill_type=2,duration=12,addtional_time=0,description='降低敵人雙防',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='初音'),skill_name = '1',skill_type=1,duration=0.05,addtional_time=0,description='',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='初音'),skill_name = '2',skill_type=1,duration=12,addtional_time=0,description='降低敵人魔防',is_weapon=1)
        Effect.objects.create(character_id=Character.objects.get(name='初音'),skill_name = '3',skill_type=2,duration=1.5,addtional_time=0,description='麻痹',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='美咲'),skill_name = '1',skill_type=1,duration=8,addtional_time=0,description='降低敵人行動速度',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='美咲'),skill_name = '2',skill_type=2,duration=0.05,addtional_time=0,description='',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='千歌(聖誕'),skill_name = '1',skill_type=1,duration=12,addtional_time=0,description='增加物攻',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='千歌(聖誕'),skill_name = '2',skill_type=1,duration=12,addtional_time=0,description='增加物理爆擊',is_weapon=1)
        Effect.objects.create(character_id=Character.objects.get(name='千歌(聖誕'),skill_name = '3',skill_type=2,duration=12,addtional_time=0,description='增加物防',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='凱留(夏日'),skill_name = '1',skill_type=1,duration=0.05,addtional_time=0,description='',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='凱留(夏日'),skill_name = '2',skill_type=1,duration=12,addtional_time=0,description='降低敵人魔防',is_weapon=1)
        Effect.objects.create(character_id=Character.objects.get(name='凱留(夏日'),skill_name = '3',skill_type=2,duration=12,addtional_time=0,description='降低敵人雙防',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='碧'),skill_name = '1',skill_type=1,duration=8,addtional_time=0,description='中毒',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='碧'),skill_name = '2',skill_type=1,duration=12,addtional_time=0,description='中猛毒',is_weapon=1)
        Effect.objects.create(character_id=Character.objects.get(name='碧'),skill_name = '3',skill_type=2,duration=2.25,addtional_time=0,description='麻痹',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='千歌'),skill_name = '1',skill_type=1,duration=12,addtional_time=0,description='增加物攻',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='千歌'),skill_name = '2',skill_type=1,duration=12,addtional_time=0,description='增加物理爆擊',is_weapon=1)
        Effect.objects.create(character_id=Character.objects.get(name='千歌'),skill_name = '3',skill_type=1,duration=8,addtional_time=0,description='持續回覆血量',is_weapon=1)
        Effect.objects.create(character_id=Character.objects.get(name='千歌'),skill_name = '4',skill_type=2,duration=12,addtional_time=0,description='降低敵人物攻',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='真步(夏日'),skill_name = '1',skill_type=1,duration=12,addtional_time=0,description='增加魔攻',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='真步(夏日'),skill_name = '2',skill_type=2,duration=0.05,addtional_time=0,description='',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='真步'),skill_name = '2',skill_type=1,duration=12,addtional_time=0,description='增加物防',is_weapon=1)
        Effect.objects.create(character_id=Character.objects.get(name='真步'),skill_name = '3',skill_type=1,duration=8.5,addtional_time=0,description='持續回血',is_weapon=1)
        Effect.objects.create(character_id=Character.objects.get(name='真步'),skill_name = '4',skill_type=2,duration=8,addtional_time=0,description='黑暗',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='優依'),skill_name = '1',skill_type=1,duration=0.05,addtional_time=0,description='',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='優依'),skill_name = '2',skill_type=1,duration=12,addtional_time=0,description='降低敵人物攻',is_weapon=1)
        Effect.objects.create(character_id=Character.objects.get(name='優依'),skill_name = '3',skill_type=2,duration=12,addtional_time=0,description='增加物防',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='雪'),skill_name = '1',skill_type=1,duration=8,addtional_time=0,description='黑暗',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='雪'),skill_name = '2',skill_type=1,duration=8,addtional_time=0,description='魅惑',is_weapon=1)
        Effect.objects.create(character_id=Character.objects.get(name='鏡華'),skill_name = '1',skill_type=1,duration=0.05,addtional_time=0,description='',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='鏡華'),skill_name = '2',skill_type=2,duration=9,addtional_time=0,description='增加魔攻',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='美咲(萬聖'),skill_name = '1',skill_type=1,duration=5,addtional_time=0,description='魅惑',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='美咲(萬聖'),skill_name = '2',skill_type=2,duration=12,addtional_time=0,description='增加魔攻',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='香織'),skill_name = '1',skill_type=1,duration=0.05,addtional_time=0,description='',is_weapon=0)
        Effect.objects.create(character_id=Character.objects.get(name='香織'),skill_name = '2',skill_type=1,duration=0.05,addtional_time=0,description='',is_weapon=1)
        Effect.objects.create(character_id=Character.objects.get(name='香織'),skill_name = '2',skill_type=1,duration=0.05,addtional_time=0,description='',is_weapon=0)
        return HttpResponse("已經加了")
    
    